function paperParamTables = paper_build_param_tables()
%PAPER_BUILD_PARAM_TABLES Build the main parameter tables that are worth reporting.
%
% The returned value is a struct array with fields:
%   - name
%   - table
%   - purpose

pNom = get_sim_params('nominal');
pDist = get_sim_params('disturbance');
pStress = get_sim_params('stress');

beam = pNom.beam;
meas = pNom.measure;

y0Nom = state_to_outputs(pNom.init.xPlant, pNom);
y0Dist = state_to_outputs(pDist.init.xPlant, pDist);
y0Stress = state_to_outputs(pStress.init.xPlant, pStress);

TbeamGeom = table( ...
    string({'Beam length'; 'Beam width'; 'Beam thickness'; 'Beam density'; 'Young modulus'; 'Cross-section area'; 'Area moment'; 'Sensor location x_s'; 'Tip location x_t'; 'Rigid-channel input gain b_{true,1}'; 'Piezo-channel input gain b_{true,2}'; 'Rigid-channel nominal gain b_{0,1}'; 'Piezo-channel nominal gain b_{0,2}'; 'Rigid-channel saturation'; 'Piezo-channel saturation'}), ...
    string({'L'; 'b'; 'h'; 'rho_b'; 'E_b'; 'A'; 'I'; 'x_s'; 'x_t'; 'bTrue(1)'; 'bTrue(2)'; 'b0(1)'; 'b0(2)'; 'u_{1,max}'; 'u_{2,max}'}), ...
    [beam.L; beam.b; beam.h; beam.rhob; beam.Eb; beam.A; beam.I; beam.xs; beam.xt; pNom.plant.bTrue(1); pNom.plant.bTrue(2); pNom.plant.b0(1); pNom.plant.b0(2); pNom.plant.umax(1); pNom.plant.umax(2)], ...
    string({'m'; 'm'; 'm'; 'kg/m^3'; 'Pa'; 'm^2'; 'm^4'; 'm'; 'm'; '-'; '-'; '-'; '-'; 'V'; 'V'}), ...
    'VariableNames', {'Parameter', 'Symbol', 'Value', 'Unit'});

Mode = (1:numel(beam.fn)).';
TbeamModes = table(Mode, beam.fn(:), beam.wn(:), beam.zeta(:), diag(beam.M), diag(beam.C), diag(beam.K), ...
    beam.Phi_s(:), beam.Phi_tip(:), beam.Gamma_p(:), beam.Bp(:), ...
    'VariableNames', {'Mode', 'fn_Hz', 'wn_rad_s', 'zeta', 'Mii', 'Cii', 'Kii', 'Phi_s', 'Phi_tip', 'Gamma_p', 'Bp'});

Point = (1:meas.numPoints).';
Tmeasurement = table(Point, meas.xNorm(:), meas.x(:), meas.weights(:), meas.PhiGrid(:,1), meas.PhiGrid(:,2), ...
    'VariableNames', {'Point', 'x_over_L', 'x_m', 'alpha', 'phi1', 'phi2'});

caseName = string({'nominal'; 'disturbance'; 'stress'});
distScale1 = [pNom.plant.distScale(1); pDist.plant.distScale(1); pStress.plant.distScale(1)];
distScale2 = [pNom.plant.distScale(2); pDist.plant.distScale(2); pStress.plant.distScale(2)];
eb2_mm = [pNom.ctrl.prop.eb(2); pDist.ctrl.prop.eb(2); pStress.ctrl.prop.eb(2)];
tEnd_s = [pNom.sim.tEnd; pDist.sim.tEnd; pStress.sim.tEnd];
outputDt_s = [pNom.sim.outputDt; pDist.sim.outputDt; pStress.sim.outputDt];
theta0_rad = [pNom.init.xPlant(1); pDist.init.xPlant(1); pStress.init.xPlant(1)];
q1_0_mm = 1000 * [pNom.init.xPlant(3); pDist.init.xPlant(3); pStress.init.xPlant(3)];
q2_0_mm = 1000 * [pNom.init.xPlant(4); pDist.init.xPlant(4); pStress.init.xPlant(4)];
y2ctrl0_mm = [y0Nom.yCtrl(2); y0Dist.yCtrl(2); y0Stress.yCtrl(2)];
y2global0_mm = [y0Nom.yGlobal(2); y0Dist.yGlobal(2); y0Stress.yGlobal(2)];
Tcases = table(caseName, distScale1, distScale2, eb2_mm, tEnd_s, outputDt_s, theta0_rad, q1_0_mm, q2_0_mm, y2ctrl0_mm, y2global0_mm, ...
    'VariableNames', {'Case', 'DistScale1', 'DistScale2', 'eb2_mm', 'tEnd_s', 'outputDt_s', 'theta0_rad', 'q1_0_mm', 'q2_0_mm', 'y2ctrl0_mm', 'y2global0_mm'});

Teso = table((1:2).', pNom.eso.wo(:), pNom.eso.rhoMap.lnftsmc_eso(:), pNom.eso.rhoMap.lnftsmc_noeso(:), ...
    pNom.eso.rhoMap.ntsmc_eso(:), pNom.eso.rhoMap.pd_eso(:), pNom.eso.rhoMap.smc_eso(:), ...
    'VariableNames', {'Channel', 'wo', 'rho_lnftsmc_eso', 'rho_lnftsmc_noeso', 'rho_ntsmc_eso', 'rho_pd_eso', 'rho_smc_eso'});

TlnftsmcEso = table((1:2).', pNom.ctrl.prop.k1(:), pNom.ctrl.prop.k2(:), pNom.ctrl.prop.k3(:), pNom.ctrl.prop.tau(:), ...
    pNom.ctrl.prop.alpha(:), pNom.ctrl.prop.beta(:), pNom.ctrl.prop.eb(:), pNom.ctrl.prop.r(:), pNom.ctrl.prop.K(:), pNom.ctrl.prop.phi(:), ...
    'VariableNames', {'Channel', 'k1', 'k2', 'k3', 'tau', 'alpha', 'beta', 'eb', 'r', 'K', 'phi'});

TlnftsmcNoEso = table((1:2).', pNom.ctrl.noeso.k1(:), pNom.ctrl.noeso.k2(:), pNom.ctrl.noeso.k3(:), pNom.ctrl.noeso.tau(:), ...
    pNom.ctrl.noeso.alpha(:), pNom.ctrl.noeso.beta(:), pNom.ctrl.noeso.eb(:), pNom.ctrl.noeso.r(:), pNom.ctrl.noeso.K(:), pNom.ctrl.noeso.phi(:), ...
    'VariableNames', {'Channel', 'k1', 'k2', 'k3', 'tau', 'alpha', 'beta', 'eb', 'r', 'K', 'phi'});

Tntsmc = table((1:2).', pNom.ctrl.nts.k1(:), pNom.ctrl.nts.k2(:), pNom.ctrl.nts.k3(:), pNom.ctrl.nts.tau(:), ...
    pNom.ctrl.nts.alpha(:), pNom.ctrl.nts.beta(:), pNom.ctrl.nts.r(:), pNom.ctrl.nts.K(:), pNom.ctrl.nts.phi(:), ...
    'VariableNames', {'Channel', 'k1', 'k2', 'k3', 'tau', 'alpha', 'beta', 'r', 'K', 'phi'});

Tsmc = table((1:2).', pNom.ctrl.smc.lambda(:), pNom.ctrl.smc.K(:), pNom.ctrl.smc.phi(:), ...
    'VariableNames', {'Channel', 'lambda', 'K', 'phi'});

Tpd = table((1:2).', pNom.ctrl.lin.lambda(:), pNom.ctrl.lin.r(:), pNom.ctrl.lin.K(:), pNom.ctrl.lin.phi(:), ...
    'VariableNames', {'Channel', 'lambda', 'r', 'K', 'phi'});

paperParamTables = struct('name', {}, 'table', {}, 'purpose', {});
paperParamTables(end+1) = struct('name', 'Param01_beam_geometry_and_inputs', 'table', TbeamGeom, ...
    'purpose', 'Main geometric, material, input-gain, and actuator-limit parameters of the beam model.');
paperParamTables(end+1) = struct('name', 'Param02_modal_properties', 'table', TbeamModes, ...
    'purpose', 'First two modal properties used by the reduced-order beam model.');
paperParamTables(end+1) = struct('name', 'Param03_measurement_points_and_weights', 'table', Tmeasurement, ...
    'purpose', 'Measurement locations, uniform weights, and mode-shape ordinates used in the whole-beam descriptor.');
paperParamTables(end+1) = struct('name', 'Param04_case_setup', 'table', Tcases, ...
    'purpose', 'Nominal, disturbance, and stress case settings including initial conditions and vibration boundary.');
paperParamTables(end+1) = struct('name', 'Param05_eso_bandwidth_and_rho', 'table', Teso, ...
    'purpose', 'ESO bandwidth and disturbance-compensation scaling factors used by each controller branch.');
paperParamTables(end+1) = struct('name', 'Param06_lnftsmc_eso_gains', 'table', TlnftsmcEso, ...
    'purpose', 'ln-NFTSMC+ESO gains reported channel by channel.');
paperParamTables(end+1) = struct('name', 'Param07_lnftsmc_noeso_gains', 'table', TlnftsmcNoEso, ...
    'purpose', 'Conservative no-ESO gains reported channel by channel.');
paperParamTables(end+1) = struct('name', 'Param08_ntsmc_gains', 'table', Tntsmc, ...
    'purpose', 'NTSMC+ESO gains reported channel by channel.');
paperParamTables(end+1) = struct('name', 'Param09_classic_smc_gains', 'table', Tsmc, ...
    'purpose', 'Classic SMC+ESO gains reported channel by channel.');
paperParamTables(end+1) = struct('name', 'Param10_pd_eso_gains', 'table', Tpd, ...
    'purpose', 'PD+ESO gains reported channel by channel.');
end
